-- user-service schema. Matches com.ecommerce.user_service.entity.UserProfile.
CREATE TABLE user_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
